### ISSUE TITLE
Correct way to pass the application_id

### ISSUE THREAD

**Issue by fabioxgn** [dropstream/omniauth-amazon-sp-api#1]
Hi @ests thanks for renaming the gem :)

I tried it and it did not work at first, so I started debugging, and here is what I found out:

To make it work, it needs to be initialized with these options (I'm using devise):

```ruby
  config.omniauth :amazon_sp_api, ENV['AMAZON_SP_API_CLIENT_ID'], ENV['AMAZON_SP_API_CLIENT_SECRET'], {
    authorize_params: {
      application_id: ENV['AMAZON_SP_API_APPLICATION_ID'],
      version: 'beta',
    },
  }
```

At first, it did not work because the `request_phase` was sending the `client_id`, so I had to add the `authorize_params` with the `application_id` so it is passed on the URL, is that correct, or do we have a better way for handling this?

**Comment by nina-saule** [comment]
This "renamed" version was not tested by me yet ;) (I plan to do that next week).

Here's the omniauth init I use (before rename) that was working:

```ruby
  provider :amazon, ENV['client_id'], ENV['client_secret'],
           redirect_uri: "#{Rails.env.production? ? 'PROD_HOST' : 'TEST_HOST'}/auth/amazon/callback",
           authorize_params: { version: 'beta', application_id: ENV['application_id'] },
           client_options: {
             authorize_url: 'https://sellercentral.amazon.com/apps/authorize/consent',
             site: Rails.env.production? ? 'https://sellingpartnerapi-na.amazon.com' : 'https://sandbox.sellingpartnerapi-na.amazon.com'
           }
```

Regarding your question: I honestly don't know if there is better way..

**Comment by fabioxgn** [comment]
Thanks. I'll test it out with this new gem version and send a PR if I find issues. I'll also add this information to the README.

**Comment by fabioxgn** [comment]
@ests I think there's a typo on the repository name. It is `ap-api` instead of `sp-api` was that your intent?

**Comment by nina-saule** [comment]
@fabioxgn fixed, thnx!
