### ISSUE TITLE
Publishing to rubygems.org

### ISSUE THREAD

**Issue by ulandj** [dropstream/omniauth-amazon-sp-api#5]
Hi @ests , @fabioxgn ,
Is there any plan to upload the gem to https://rubygems.org/ so people could install it simply like `gem install omniauth-amazon-sp-api` ?

**Comment by nina-saule** [comment]
Right, it will be done this weekend.

**Comment by nina-saule** [comment]
https://rubygems.org/gems/omniauth-amazon-sp-api

**Comment by ulandj** [comment]
Amazing! Thanks
